const APP_CONFIG={version:"6.4",updated:"September 2026",fxDate:"31 August 2026",fxSource:"Indicative planning rates based on recent public reference rates",
currencies:{
CAD:{country:"Canada",name:"Canadian Dollar",symbol:"C$",locale:"en-CA",rate:1,decimals:0},
AUD:{country:"Australia",name:"Australian Dollar",symbol:"A$",locale:"en-AU",rate:.9971,decimals:0},
NZD:{country:"New Zealand",name:"New Zealand Dollar",symbol:"NZ$",locale:"en-NZ",rate:.8247,decimals:0},
USD:{country:"United States",name:"US Dollar",symbol:"US$",locale:"en-US",rate:1.3861,decimals:0},
EUR:{country:"Spain",name:"Euro",symbol:"€",locale:"en-IE",rate:1.6147,decimals:2},
GBP:{country:"United Kingdom",name:"British Pound",symbol:"£",locale:"en-GB",rate:1.8836,decimals:2},
JPY:{country:"Japan",name:"Japanese Yen",symbol:"¥",locale:"ja-JP",rate:.0087,decimals:0},
KRW:{country:"South Korea",name:"South Korean Won",symbol:"₩",locale:"ko-KR",rate:.001003,decimals:0},
CHF:{country:"Switzerland",name:"Swiss Franc",symbol:"CHF",locale:"de-CH",rate:1.7237,decimals:2},
SGD:{country:"Singapore",name:"Singapore Dollar",symbol:"S$",locale:"en-SG",rate:1.0904,decimals:2},
HKD:{country:"Hong Kong",name:"Hong Kong Dollar",symbol:"HK$",locale:"zh-HK",rate:.1768,decimals:2},
TWD:{country:"Taiwan",name:"New Taiwan Dollar",symbol:"NT$",locale:"zh-TW",rate:.04374,decimals:0},
INR:{country:"India",name:"Indian Rupee",symbol:"₹",locale:"en-IN",rate:.01451,decimals:0},
BRL:{country:"Brazil",name:"Brazilian Real",symbol:"R$",locale:"pt-BR",rate:.2684,decimals:2},
MXN:{country:"Mexico",name:"Mexican Peso",symbol:"MX$",locale:"es-MX",rate:.08168,decimals:0},
PLN:{country:"Poland",name:"Polish Zloty",symbol:"zł",locale:"pl-PL",rate:.3727,decimals:2},
CZK:{country:"Czechia",name:"Czech Koruna",symbol:"Kč",locale:"cs-CZ",rate:.0668,decimals:2},
DKK:{country:"Denmark",name:"Danish Krone",symbol:"kr",locale:"da-DK",rate:.2158,decimals:2},
SEK:{country:"Sweden",name:"Swedish Krona",symbol:"kr",locale:"sv-SE",rate:.1455,decimals:2},
NOK:{country:"Norway",name:"Norwegian Krone",symbol:"kr",locale:"nb-NO",rate:.1486,decimals:2},
ZAR:{country:"South Africa",name:"South African Rand",symbol:"R",locale:"en-ZA",rate:.08667,decimals:2},
THB:{country:"Thailand",name:"Thai Baht",symbol:"฿",locale:"th-TH",rate:.04216,decimals:0},
MYR:{country:"Malaysia",name:"Malaysian Ringgit",symbol:"RM",locale:"ms-MY",rate:.3437,decimals:2},
ILS:{country:"Israel",name:"Israeli New Shekel",symbol:"₪",locale:"he-IL",rate:.4660,decimals:2},
IDR:{country:"Indonesia",name:"Indonesian Rupiah",symbol:"Rp",locale:"id-ID",rate:.000078,decimals:0},
PHP:{country:"Philippines",name:"Philippine Peso",symbol:"₱",locale:"en-PH",rate:.02225,decimals:0},
CNY:{country:"China",name:"Chinese Yuan",symbol:"¥",locale:"zh-CN",rate:.2063,decimals:0},
TRY:{country:"Türkiye",name:"Turkish Lira",symbol:"₺",locale:"tr-TR",rate:.0288,decimals:2},
VND:{country:"Vietnam",name:"Vietnamese Dong",symbol:"₫",locale:"vi-VN",rate:.0000525,decimals:0},
CLP:{country:"Chile",name:"Chilean Peso",symbol:"CLP$",locale:"es-CL",rate:.00145,decimals:0},
ARS:{country:"Argentina",name:"Argentine Peso",symbol:"ARS$",locale:"es-AR",rate:.00106,decimals:0},
COP:{country:"Colombia",name:"Colombian Peso",symbol:"COL$",locale:"es-CO",rate:.00035,decimals:0},
PEN:{country:"Peru",name:"Peruvian Sol",symbol:"S/",locale:"es-PE",rate:.4139,decimals:2},
HUF:{country:"Hungary",name:"Hungarian Forint",symbol:"Ft",locale:"hu-HU",rate:.00442,decimals:0},
RON:{country:"Romania",name:"Romanian Leu",symbol:"lei",locale:"ro-RO",rate:.3067,decimals:2},
ISK:{country:"Iceland",name:"Icelandic Króna",symbol:"kr",locale:"is-IS",rate:.01145,decimals:0}},
countries:[
["Australia","AUD"],["New Zealand","NZD"],["United States","USD"],["United Kingdom","GBP"],["Spain","EUR"],["France","EUR"],["Germany","EUR"],["Ireland","EUR"],["Italy","EUR"],["Netherlands","EUR"],["Belgium","EUR"],["Austria","EUR"],["Portugal","EUR"],["Finland","EUR"],["Japan","JPY"],["South Korea","KRW"],["Taiwan","TWD"],["Switzerland","CHF"],["Mexico","MXN"],["Brazil","BRL"],["Poland","PLN"],["Czechia","CZK"],["Denmark","DKK"],["Sweden","SEK"],["Norway","NOK"],["Singapore","SGD"],["Hong Kong","HKD"],["India","INR"],["South Africa","ZAR"],["Thailand","THB"],["Malaysia","MYR"],["Israel","ILS"],["Indonesia","IDR"],["Philippines","PHP"],["China","CNY"],["Türkiye","TRY"],["Vietnam","VND"],["Chile","CLP"],["Argentina","ARS"],["Colombia","COP"],["Peru","PEN"],["Hungary","HUF"],["Romania","RON"],["Greece","EUR"],["Iceland","ISK"]],
cities:{
vancouver:{name:"Vancouver",province:"British Columbia",provinceCode:"BC",minimumWage:18.25,accommodation:{staff:700,shared:900,privateRoom:1300,apartment:2377},monthly:{food:500,transport:117,phone:35,entertainment:250,misc:200},defaultWage:22},
whistler:{name:"Whistler",province:"British Columbia",provinceCode:"BC",minimumWage:18.25,accommodation:{staff:500,shared:1300,privateRoom:1700,apartment:2657},monthly:{food:550,transport:55,phone:35,entertainment:350,misc:200},defaultWage:22},
banff:{name:"Banff",province:"Alberta",provinceCode:"AB",minimumWage:15,accommodation:{staffBunk:400,staffShared:525,shared:1000,privateRoom:1300,apartment:1499},monthly:{food:550,transport:30,phone:35,entertainment:300,misc:200},defaultWage:20},
calgary:{name:"Calgary",province:"Alberta",provinceCode:"AB",minimumWage:15,accommodation:{staff:600,shared:750,privateRoom:900,apartment:1513},monthly:{food:450,transport:126,phone:35,entertainment:250,misc:200},defaultWage:20},
toronto:{name:"Toronto",province:"Ontario",provinceCode:"ON",minimumWage:17.60,minimumWageNext:17.95,minimumWageNextDate:"October 1, 2026",accommodation:{staff:700,shared:800,privateRoom:1100,apartment:2234},monthly:{food:500,transport:130,phone:35,entertainment:250,misc:200},defaultWage:20},
montreal:{name:"Montreal",province:"Quebec",provinceCode:"QC",minimumWage:16.60,accommodation:{staff:600,shared:700,privateRoom:950,apartment:1769},monthly:{food:450,transport:100,phone:35,entertainment:250,misc:200},defaultWage:19}},
jobTypes:{hospitality:{label:"Hospitality / server",wage:22,hours:32},ski:{label:"Ski resort",wage:21,hours:32},hotel:{label:"Hotel",wage:21,hours:32},retail:{label:"Retail",wage:20,hours:30},construction:{label:"Construction / trades",wage:28,hours:38},farm:{label:"Farm / seasonal",wage:20,hours:38},office:{label:"Office / professional",wage:28,hours:35},unknown:{label:"Not sure yet",wage:22,hours:32}},
taxModel:{year:2026,federalBPA:16452,cea:1501,cpp:{rate:.0595,ympe:74600,exemption:3500,cpp2Rate:.04,yampe:85000},ei:{rate:.0163,maxInsurable:68900},provinces:{BC:{bpa:13216,rates:[[50363,.056],[100728,.077],[115648,.105],[140430,.1229],[190405,.147],[265545,.168],[Infinity,.205]]},AB:{bpa:22769,rates:[[61200,.08],[154259,.10],[185111,.12],[246813,.13],[370220,.14],[Infinity,.15]]},ON:{bpa:12989,rates:[[53891,.0505],[107785,.0915],[150000,.1116],[220000,.1216],[Infinity,.1316]]},QC:{bpa:18952,rates:[[54345,.14],[108680,.19],[132245,.24],[Infinity,.2575]]}}},
lifestyle:{budget:{food:350,entertainment:100,misc:100},normal:{food:500,entertainment:250,misc:200},social:{food:650,entertainment:450,misc:300}}};