let selectedCity="whistler",selectedLife="budget",selectedAccommodation="staff",homeCurrency=null,homeCountry=null;
const $=id=>document.getElementById(id), val=id=>Math.max(0,Number($(id)?.value)||0);
const currency=()=>APP_CONFIG.currencies[homeCurrency||"CAD"];
const toCad=n=>Math.max(0,n)*currency().rate;
const fromCad=n=>Math.max(0,n)/currency().rate;
const money=(n,code=homeCurrency)=>{const c=APP_CONFIG.currencies[code||homeCurrency||"CAD"];const digits=c.decimals;return c.symbol+Number(Math.max(0,n)).toLocaleString(c.locale,{minimumFractionDigits:digits,maximumFractionDigits:digits});};
const cadMoney=n=>"C$"+Math.round(Math.max(0,n)).toLocaleString("en-CA");
const signed=n=>(n>=0?"+":"−")+money(Math.abs(n));
const city=()=>APP_CONFIG.cities[selectedCity];
const currencyInputs=["savings","flight","rent","temporaryRate","deposit","wage","food","transport","phone","entertainment","misc","visa","workPermit","biometrics","insurance","gear","otherSetup"];
const rangePairs=[["savingsRange","savings"],["flightRange","flight"],["rentRange","rent"],["temporaryRateRange","temporaryRate"],["depositRange","deposit"],["wageRange","wage"],["hoursRange","hours"],["taxRange","tax"],["foodRange","food"],["transportRange","transport"],["phoneRange","phone"],["entertainmentRange","entertainment"],["miscRange","misc"]];

function populateCountries(){const select=$("originCountry");if(!select)return;const entries=APP_CONFIG.countries||[];select.innerHTML='<option value="">Select your country…</option>'+entries.map(([country,code])=>{const c=APP_CONFIG.currencies[code];return `<option value="${code}" data-country="${country}">${country} — ${c.name} (${c.symbol})</option>`}).join("");}
function updateOriginPreview(){const c=currency();const preview=$("originPreview"),btn=$("startBudget");if(!homeCurrency){preview.innerHTML='<span>Currency</span><strong>—</strong><small>Choose a country to continue.</small>';btn.disabled=true;return}preview.innerHTML=`<span>Your home currency</span><strong>${c.symbol} ${homeCurrency}</strong><small>1 ${homeCurrency} ≈ ${cadMoney(c.rate)} CAD · planning rate</small>`;btn.disabled=false;}
function setCurrency(code,{preserveCad=true}={}){if(!APP_CONFIG.currencies[code])return;const previous=homeCurrency;const cadValues={};if(previous&&preserveCad){currencyInputs.forEach(id=>{if($(id))cadValues[id]=toCad(val(id));});}homeCurrency=code;localStorage.setItem("whhqHomeCurrency",code);document.documentElement.dataset.currency=code;document.querySelectorAll(".currency-symbol").forEach(el=>el.textContent=currency().symbol);$("currencyName").textContent=`${homeCountry||currency().country} · ${currency().name} (${code})`;$("currencyRate").textContent=`1 ${code} ≈ ${currency().rate.toFixed(currency().rate<.1?5:4)} CAD`;$("fxNote").textContent=`Indicative planning rate, reference date ${APP_CONFIG.fxDate}. Rates move; use this for planning, not a guaranteed conversion.`;updateInputRanges();if(previous&&preserveCad){currencyInputs.forEach(id=>{if($(id)&&cadValues[id]!=null)$(id).value=roundInput(fromCad(cadValues[id]),id);});}else setInitialHomeValues();setCityDefaults();recalc();updateOriginPreview();}
function roundInput(n,id){const d=currency().decimals;const step=(id==="wage"||id==="temporaryRate"||id==="rent"||id==="food"||id==="entertainment"||id==="misc")? (d?0.01:1) : (d?0.01:1);return Number(n.toFixed(Math.min(2,d+1)));}
function updateInputRanges(){const ranges={savings:[0,50000,100],flight:[0,5000,50],rent:[0,3500,25],temporaryRate:[0,2000,25],deposit:[0,5000,50],wage:[0,50,.25],food:[0,2000,25],transport:[0,1000,5],phone:[0,300,5],entertainment:[0,2000,25],misc:[0,1500,25]};Object.entries(ranges).forEach(([id,[min,max,step]])=>{const r=$(id+"Range"),i=$(id);if(!r||!i)return;r.min=fromCad(min);r.max=fromCad(max);r.step=currency().decimals?Math.max(step/currency().rate,0.01):Math.max(Math.round(step/currency().rate),1);});}
function setInitialHomeValues(){const defaults={savings:20000,flight:1200,temporaryRate:400,deposit:500,visa:184.75,workPermit:100,biometrics:85,insurance:1000,gear:750,otherSetup:300};Object.entries(defaults).forEach(([id,cad])=>{if($(id))$(id).value=roundInput(fromCad(cad),id)});}
function pair(rangeId,inputId){const r=$(rangeId),i=$(inputId);if(!r||!i)return;r.addEventListener("input",()=>{i.value=r.value;recalc()});i.addEventListener("input",()=>{let n=Number(i.value)||0;n=Math.max(0,n);i.value=n;r.value=Math.max(Number(r.min)||0,Math.min(Number(r.max)||n,n));recalc()});}
function accommodationOptions(){const c=city(),opts=selectedCity==="banff"?[["staffBunk","Staff bunk",c.accommodation.staffBunk,"Best-case staff housing"],["staffShared","Staff shared room",c.accommodation.staffShared,"Typical subsidised staff option"],["shared","Shared bedroom",c.accommodation.shared,"Shared rental"],["privateRoom","Private room",c.accommodation.privateRoom,"Your own bedroom"],["apartment","Private apartment",c.accommodation.apartment,"Full apartment"]]:[["staff","Staff accommodation",c.accommodation.staff,"Employer-provided / employee housing"],["shared","Shared bedroom",c.accommodation.shared,"Shared rental"],["privateRoom","Private room",c.accommodation.privateRoom,"Your own bedroom"],["apartment","Private apartment",c.accommodation.apartment,"Full apartment"]];$("accommodationOptions").innerHTML=opts.map(o=>`<button type="button" class="option ${o[0]===selectedAccommodation?"selected":""}" data-accommodation="${o[0]}" data-value="${o[2]}"><span class="radio"></span><span><b>${o[1]}</b><small>${o[3]}</small></span><strong>${money(fromCad(o[2]))}<small>/ month</small></strong></button>`).join("");document.querySelectorAll(".option").forEach(b=>b.addEventListener("click",()=>{selectedAccommodation=b.dataset.accommodation;$("rent").value=roundInput(fromCad(Number(b.dataset.value)),"rent");$("rentRange").value=Number($("rent").value);recalc();accommodationOptions()}));}
function applyLifestyle(){const c=city(),l=APP_CONFIG.lifestyle[selectedLife];let food=l.food,ent=l.entertainment,misc=l.misc;if(selectedLife==="normal"){food=c.monthly.food;ent=c.monthly.entertainment;misc=c.monthly.misc}if(selectedLife==="budget"&&(selectedCity==="whistler"||selectedCity==="banff"))food=400;$("food").value=roundInput(fromCad(food),"food");$("entertainment").value=roundInput(fromCad(ent),"entertainment");$("misc").value=roundInput(fromCad(misc),"misc");document.querySelectorAll(".lifestyle").forEach(x=>x.classList.toggle("selected",x.dataset.life===selectedLife));syncRanges();recalc()}
function setCityDefaults(){const c=city();$("wage").value=roundInput(fromCad(c.defaultWage),"wage");$("transport").value=roundInput(fromCad(c.monthly.transport),"transport");$("phone").value=roundInput(fromCad(c.monthly.phone),"phone");$("wageHint").textContent=`Canadian minimum wage: C$${c.minimumWage.toFixed(2)}/hour · about ${money(fromCad(c.minimumWage))}/hour in your home currency${c.minimumWageNext?` (rising to C$${c.minimumWageNext.toFixed(2)} on ${c.minimumWageNextDate})`:""}.`;selectedAccommodation=selectedCity==="banff"?"staffShared":"staff";$("rent").value=roundInput(fromCad(selectedCity==="banff"?c.accommodation.staffShared:c.accommodation.staff),"rent");syncRanges();accommodationOptions();applyLifestyle()}
function syncRanges(){rangePairs.forEach(([rId,iId])=>{const r=$(rId),i=$(iId);if(r&&i){r.value=Math.max(Number(r.min)||0,Math.min(Number(r.max)||0,Number(i.value)||0));}})}
function cadInput(id){return toCad(val(id));}
function recalc(){if(!homeCurrency)return;const c=city(),savings=cadInput("savings"),temporary=val("temporaryWeeks")*cadInput("temporaryRate"),setup=cadInput("flight")+cadInput("visa")+cadInput("workPermit")+cadInput("biometrics")+cadInput("insurance")+cadInput("gear")+cadInput("otherSetup")+temporary+cadInput("deposit"),rent=cadInput("rent"),other=cadInput("food")+cadInput("transport")+cadInput("phone")+cadInput("entertainment")+cadInput("misc"),burn=rent+other,gross=cadInput("wage")*val("hours")*52/12,income=$("working").checked?gross*(1-Math.min(60,val("tax"))/100):0,surplus=income-burn,cash=savings-setup,noWork=burn?cash/burn:99,deficit=Math.max(0,burn-income),workRunway=deficit?cash/deficit:99,recommendedLow=setup+burn*3,recommendedHigh=setup+burn*6;
$("savingsCad").textContent=cadMoney(savings);$("resultCity").textContent=c.name;$("recommended").textContent=`${money(fromCad(recommendedLow))}–${money(fromCad(recommendedHigh))}`;$("recommendedCad").textContent=`CAD equivalent: ${cadMoney(recommendedLow)}–${cadMoney(recommendedHigh)}`;$("rSavings").textContent=money(fromCad(savings));$("rSetup").textContent=money(fromCad(setup));$("rCash").textContent=money(fromCad(cash));$("rRent").textContent=money(fromCad(rent));$("rOther").textContent=money(fromCad(other));$("rBurn").textContent=money(fromCad(burn));$("rIncome").textContent=money(fromCad(income));$("rSurplus").textContent=signed(fromCad(surplus));$("rNoWork").textContent=cash<=0?"No buffer":`${Math.max(0,noWork).toFixed(1)} months`;$("rWithWork").textContent=deficit===0?"Self-sustaining":`${Math.max(0,workRunway).toFixed(1)} months`;$("cadSummary").textContent=`${cadMoney(recommendedLow)}–${cadMoney(recommendedHigh)} recommended starting cash`;
let score=Math.round(Math.max(0,Math.min(100,50+(cash>0?Math.min(30,cash/(burn||1)*5):-30)+(surplus>=0?20:Math.max(-20,surplus/(burn||1)*20)))));$("score").textContent=score;$("scoreBar").style.width=score+"%";let st="Strong",cl="good";if(cash<=0||noWork<2){st="High risk";cl="bad"}else if(noWork<4||surplus<0){st="Tight";cl="warn"}$("status").textContent=st;$("status").className=`status ${cl}`;$("callout").textContent=cash<=0?`Your ${currency().name} savings don't cover the estimated arrival and setup costs.`:!$("working").checked?`Without employment, your current plan gives you roughly ${Math.max(0,noWork).toFixed(1)} months of runway.`:surplus>=0?`Your planned income is higher than your estimated monthly expenses. Your savings could remain largely intact while you work.`:`Your estimated monthly deficit is ${money(Math.abs(fromCad(surplus)))}. Finding work quickly or reducing accommodation costs would materially improve your runway.`;}
function showCalculator(){$("origin").classList.add("hidden");$("calculator").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});}
function captureCadValues(){const out={};if(!homeCurrency)return out;currencyInputs.forEach(id=>{if($(id))out[id]=cadInput(id)});return out;}
function bindEvents(){$("originCountry").addEventListener("change",e=>{if(e.target.value){homeCurrency=e.target.value;homeCountry=e.target.options[e.target.selectedIndex].dataset.country||currency().country;updateOriginPreview();}});$("startBudget").addEventListener("click",()=>{setCurrency(homeCurrency,{preserveCad:false});showCalculator();});$("changeCountry").addEventListener("click",()=>{$("calculator").classList.add("hidden");$("origin").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});});document.querySelectorAll(".city-card").forEach(b=>b.addEventListener("click",()=>{selectedCity=b.dataset.city;document.querySelectorAll(".city-card").forEach(x=>x.classList.toggle("selected",x.dataset.city===selectedCity));setCityDefaults()}));document.querySelectorAll(".lifestyle").forEach(b=>b.addEventListener("click",()=>{selectedLife=b.dataset.life;applyLifestyle()}));document.querySelectorAll("input,select").forEach(e=>e.addEventListener("input",()=>{if(e.id!=="originCountry")recalc()}));$("working").addEventListener("change",()=>{$("workFields").classList.toggle("disabled",!$("working").checked);recalc()});$("printBtn").addEventListener("click",()=>window.print());rangePairs.forEach(x=>pair(x[0],x[1]));}
populateCountries();bindEvents();const saved=localStorage.getItem("whhqHomeCurrency");if(saved&&APP_CONFIG.currencies[saved]){$("originCountry").value=saved;homeCurrency=saved;homeCountry=$("originCountry").options[$("originCountry").selectedIndex]?.dataset.country||currency().country;updateOriginPreview();}else updateOriginPreview();
