var displayCurrency="home";
let selectedCity="whistler",selectedLife="normal",selectedAccommodation="staff",homeCurrency=null,homeCountry=null;
const $=id=>document.getElementById(id), val=id=>Math.max(0,Number($(id)?.value)||0);
const currency=()=>APP_CONFIG.currencies[homeCurrency||"CAD"];
const toCad=n=>Math.max(0,n)*currency().rate;
const fromCad=n=>Math.max(0,n)/currency().rate;
const money=(n,code=homeCurrency)=>{const c=APP_CONFIG.currencies[code||homeCurrency||"CAD"];return c.symbol+Math.round(Math.max(0,n)).toLocaleString(c.locale,{maximumFractionDigits:0});};
const cadMoney=n=>"C$"+Math.round(Math.max(0,n)).toLocaleString("en-CA");
const signed=n=>(n>=0?"+":"−")+money(Math.abs(n));
const city=()=>APP_CONFIG.cities[selectedCity];
const currencyInputs=["savings","flight","rent","temporaryRate","deposit","wage","food","transport","phone","entertainment","misc","visa","workPermit","biometrics","insurance","gear","otherSetup"];
const rangePairs=[["savingsRange","savings"],["flightRange","flight"],["rentRange","rent"],["temporaryRateRange","temporaryRate"],["depositRange","deposit"],["wageRange","wage"],["hoursRange","hours"],["foodRange","food"],["transportRange","transport"],["phoneRange","phone"],["entertainmentRange","entertainment"],["miscRange","misc"]];

function populateCountries(){const select=$("originCountry");if(!select)return;const entries=APP_CONFIG.countries||[];select.innerHTML='<option value="">Select your country…</option>'+entries.map(([country,code])=>{const c=APP_CONFIG.currencies[code];return `<option value="${code}" data-country="${country}">${country} — ${c.name} (${c.symbol})</option>`}).join("");}
function updateOriginPreview(){const c=currency(),preview=$("originPreview"),btn=$("startBudget");if(!preview||!btn)return;if(!homeCurrency){preview.innerHTML='<span>Currency</span><strong>—</strong><small>Choose a country to continue.</small>';btn.disabled=true;return}preview.innerHTML=`<span>Your home currency</span><strong>${c.symbol} ${homeCurrency}</strong><small>1 ${homeCurrency} ≈ ${cadMoney(c.rate)} CAD · planning rate</small>`;btn.disabled=false;}
function roundInput(n){return Math.round(Number(n)||0)}
function setCurrency(code,{preserveCad=true}={}){if(!APP_CONFIG.currencies[code])return;const previous=homeCurrency,cadValues={};if(previous&&preserveCad)currencyInputs.forEach(id=>{if($(id))cadValues[id]=cadInput(id)});homeCurrency=code;localStorage.setItem("whhqHomeCurrency",code);document.documentElement.dataset.currency=code;document.querySelectorAll(".currency-symbol").forEach(el=>el.textContent=displayCurrency==="cad"?"C$":currency().symbol);if($("currencyName"))$("currencyName").textContent=`${homeCountry||currency().country} · ${currency().name} (${code})`;if($("currencyRate"))$("currencyRate").textContent=`1 ${code} ≈ ${Math.round(currency().rate*100)/100} CAD`;if($("fxNote"))$("fxNote").textContent=`Indicative planning rate, reference date ${APP_CONFIG.fxDate}.`;updateInputRanges();if(previous&&preserveCad)currencyInputs.forEach(id=>{if($(id)&&cadValues[id]!=null)$(id).value=displayCurrency==="cad"?Math.round(cadValues[id]):roundInput(fromCad(cadValues[id]))});else setInitialHomeValues();setCityDefaults();recalc();updateOriginPreview();}
function updateInputRanges(){const ranges={savings:[0,50000,1],flight:[0,5000,1],rent:[0,3500,1],temporaryRate:[0,2000,1],deposit:[0,5000,1],wage:[0,50,1],food:[0,2000,1],transport:[0,1000,1],phone:[0,300,1],entertainment:[0,2000,1],misc:[0,1500,1]};Object.entries(ranges).forEach(([id,[min,max,step]])=>{const r=$(id+"Range"),i=$(id);if(!r||!i)return;r.min=Math.round(fromCad(min));r.max=Math.round(fromCad(max));r.step=step;});}
function setInitialHomeValues(){const defaults={savings:20000,flight:1200,temporaryRate:400,deposit:500,visa:184.75,workPermit:100,biometrics:85,insurance:1000,gear:750,otherSetup:300};Object.entries(defaults).forEach(([id,cad])=>{if($(id))$(id).value=displayCurrency==="cad"?Math.round(cad):roundInput(fromCad(cad))});}
function setCityDefaults(){const c=city(),show=n=>displayCurrency==="cad"?Math.round(n):roundInput(fromCad(n));const jt=APP_CONFIG.jobTypes?.[$("jobType")?.value||"hospitality"];$("wage").value=show(jt?.wage||c.defaultWage);$("hours").value=jt?.hours||32;$("transport").value=show(c.monthly.transport);$("phone").value=show(c.monthly.phone);if($("wageHint"))$("wageHint").textContent=`${c.name} planning wage: C$${Math.round(jt?.wage||c.defaultWage)}/hour · ${c.name} minimum wage is C$${Math.round(c.minimumWage)}/hour.`;selectedAccommodation=selectedCity==="banff"?"staffShared":"staff";$("rent").value=show(selectedCity==="banff"?c.accommodation.staffShared:c.accommodation.staff);syncRanges();accommodationOptions();applyLifestyle();}
function syncRanges(){rangePairs.forEach(([rId,iId])=>{const r=$(rId),i=$(iId);if(r&&i){r.value=Math.max(Number(r.min)||0,Math.min(Number(r.max)||0,Math.round(Number(i.value)||0)))}})}
function pair(rangeId,inputId){const r=$(rangeId),i=$(inputId);if(!r||!i)return;r.addEventListener("input",()=>{i.value=Math.round(Number(r.value)||0);recalc()});i.addEventListener("input",()=>{i.value=Math.max(0,Math.round(Number(i.value)||0));r.value=Math.max(Number(r.min)||0,Math.min(Number(r.max)||0,Number(i.value)||0));recalc()})}
function accommodationOptions(){const c=city(),opts=selectedCity==="banff"?[["staffBunk","Staff bunk",c.accommodation.staffBunk,"Best-case staff housing"],["staffShared","Staff shared room",c.accommodation.staffShared,"Typical subsidised staff option"],["shared","Shared bedroom",c.accommodation.shared,"Shared rental"],["privateRoom","Private room",c.accommodation.privateRoom,"Your own bedroom"],["apartment","Private apartment",c.accommodation.apartment,"Full apartment"]]:[["staff","Staff accommodation",c.accommodation.staff,"Employer-provided / employee housing"],["shared","Shared bedroom",c.accommodation.shared,"Shared rental"],["privateRoom","Private room",c.accommodation.privateRoom,"Your own bedroom"],["apartment","Private apartment",c.accommodation.apartment,"Full apartment"]];if($("accommodationOptions"))$("accommodationOptions").innerHTML=opts.map(o=>`<button type="button" class="option ${o[0]===selectedAccommodation?"selected":""}" data-accommodation="${o[0]}" data-value="${o[2]}"><span class="radio"></span><span><b>${o[1]}</b><small>${o[3]}</small></span><strong>${money(fromCad(o[2]))}<small>/ month</small></strong></button>`).join("");document.querySelectorAll(".option").forEach(b=>b.addEventListener("click",()=>{selectedAccommodation=b.dataset.accommodation;$("rent").value=displayCurrency==="cad"?Math.round(Number(b.dataset.value)):roundInput(fromCad(Number(b.dataset.value)));$("rentRange").value=Number($("rent").value);recalc();accommodationOptions()}));}
function applyLifestyle(){const c=city(),l=APP_CONFIG.lifestyle[selectedLife]||APP_CONFIG.lifestyle.normal;let food=l.food,ent=l.entertainment,misc=l.misc;if(selectedLife==="normal"){food=c.monthly.food;ent=c.monthly.entertainment;misc=c.monthly.misc}if(selectedLife==="budget"&&(selectedCity==="whistler"||selectedCity==="banff"))food=400;["food","entertainment","misc"].forEach((id,i)=>{const cad=[food,ent,misc][i];if($(id))$(id).value=displayCurrency==="cad"?Math.round(cad):roundInput(fromCad(cad))});document.querySelectorAll(".lifestyle").forEach(x=>x.classList.toggle("selected",x.dataset.life===selectedLife));syncRanges();recalc();}
function cadInput(id){const n=val(id);return displayCurrency==="cad"?n:toCad(n)}
function bracketTax(income,brackets){let tax=0,prev=0;for(const [top,rate] of brackets){const taxable=Math.max(0,Math.min(income,top)-prev);tax+=taxable*rate;if(income<=top)break;prev=top}return tax}
function taxEstimate(annualGross,province){
  const tm=APP_CONFIG.taxModel,prov=tm.provinces[province]||tm.provinces.BC;
  const federalRaw=bracketTax(annualGross,tm.federalRates);
  const federalCredit=Math.min(annualGross,tm.federalBPA)*0.14+Math.min(annualGross,tm.cea)*0.14;
  let fed=Math.max(0,federalRaw-federalCredit);
  let provincial=Math.max(0,bracketTax(annualGross,prov.rates)-Math.min(annualGross,prov.bpa)*prov.rates[0][1]);
  if(province==="ON"){
    const surtax1=Math.max(0,provincial-5818)*0.20;
    const surtax2=Math.max(0,provincial-7446)*0.16;
    provincial+=surtax1+surtax2;
  }
  if(province==="QC"){
    // Quebec residents receive a federal abatement; QPP/EI/QPIP use Quebec rates.
    fed=Math.max(0,fed*(1-0.165));
  }
  const payroll=province==="QC"?(()=>{
    const qpp=Math.max(0,Math.min(annualGross,tm.cpp.ympe)-tm.cpp.exemption)*tm.cpp.qppRate;
    const qpp2=annualGross>tm.cpp.ympe?Math.min(annualGross-tm.cpp.ympe,tm.cpp.yampe-tm.cpp.ympe)*tm.cpp.cpp2Rate:0;
    const ei=Math.min(annualGross,tm.ei.maxInsurable)*tm.ei.qcRate;
    const qpip=Math.min(annualGross,tm.qpip.maxInsurable)*tm.qpip.rate;
    return {total:qpp+qpp2+ei+qpip,qpp,qpp2,ei,qpip};
  })():(()=>{
    const cpp=Math.max(0,Math.min(annualGross,tm.cpp.ympe)-tm.cpp.exemption)*tm.cpp.rate;
    const cpp2=annualGross>tm.cpp.ympe?Math.min(annualGross-tm.cpp.ympe,tm.cpp.yampe-tm.cpp.ympe)*tm.cpp.cpp2Rate:0;
    const ei=Math.min(annualGross,tm.ei.maxInsurable)*tm.ei.rate;
    return {total:cpp+cpp2+ei,cpp,cpp2,ei};
  })();
  return {tax:fed+provincial,payroll:payroll.total,net:Math.max(0,annualGross-fed-provincial-payroll.total),federal:fed,provincial,cpp:payroll.cpp||payroll.qpp,cpp2:payroll.cpp2||payroll.qpp2,ei:payroll.ei,qpip:payroll.qpip||0};
}
function incomeModel(){const c=city(),working=$("working")?.checked!==false, wage=cadInput("wage")||c.defaultWage, hours=val("hours")||32, grossMonthly=wage*hours*52/12, annual=grossMonthly*12, tx=working?taxEstimate(annual,c.provinceCode):{tax:0,payroll:0,net:0}, netMonthly=tx.net/12, quickWork=$("quickWork")?.value!=="no";if(document.body.classList.contains("mode-quick"))return quickWork?{grossMonthly,annual,netMonthly:netMonthly||grossMonthly*.8,taxMonthly:tx.tax/12,payrollMonthly:tx.payroll/12}: {grossMonthly:0,annual:0,netMonthly:0,taxMonthly:0,payrollMonthly:0};return {grossMonthly,annual,netMonthly:working?netMonthly:0,taxMonthly:working?tx.tax/12:0,payrollMonthly:working?tx.payroll/12:0}}
function projectedCash(cash,burn,income,months=12,delayWeeks=0){let balance=cash;for(let m=1;m<=months;m++){let inc=income;if(m===1)inc=income*Math.max(0,1-delayWeeks/4);balance+=inc-burn}return balance}
function updateCashChart(cash,burn,income,months=12){const chart=$("cashChart"),labels=$("cashLabels"),summary=$("cashChartSummary");if(!chart||!labels)return;const vals=[];let c=cash;for(let m=0;m<=months;m++){vals.push(c);if(m<months)c+=income-burn}const points=vals.filter((_,i)=>i===0||i===months||i%2===0),pointMonths=vals.map((_,i)=>i).filter(i=>i===0||i===months||i%2===0),min=Math.min(...vals,0),max=Math.max(...vals,1),range=Math.max(max-min,1);chart.innerHTML=points.map((v,i)=>{const month=pointMonths[i];return `<div class="cash-bar" style="height:${Math.max(10,((v-min)/range)*128)}px" title="${month===0?"Now":"Month "+month}: ${money(fromCad(v))}"></div>`}).join("");labels.innerHTML=pointMonths.map(i=>`<span>${i===0?"Now":"M"+i}</span>`).join("");if(summary)summary.innerHTML=`<span>Start <b>${money(fromCad(vals[0]))}</b></span><span>Projected end <b>${money(fromCad(vals[vals.length-1]))}</b></span>`}
function recalc(){if(!homeCurrency||!$("calculator")||$("calculator").classList.contains("hidden"))return;const c=city(),savings=cadInput("savings"),temporary=val("temporaryWeeks")*cadInput("temporaryRate"),setup=cadInput("flight")+cadInput("visa")+cadInput("workPermit")+cadInput("biometrics")+cadInput("insurance")+cadInput("gear")+cadInput("otherSetup")+temporary+cadInput("deposit"),rent=cadInput("rent");let food,ent,misc;if(document.body.classList.contains("mode-quick")){const q=$("quickLifestyle")?.value||"normal";const l=APP_CONFIG.lifestyle[q];food=q==="normal"?c.monthly.food:l.food;ent=q==="normal"?c.monthly.entertainment:l.entertainment;misc=q==="normal"?c.monthly.misc:l.misc;if(q==="budget"&&(selectedCity==="whistler"||selectedCity==="banff"))food=400}else{food=cadInput("food");ent=cadInput("entertainment");misc=cadInput("misc")}const transport=cadInput("transport"),phone=cadInput("phone"),other=food+transport+phone+ent+misc,burn=rent+other,gross=cadInput("wage")*val("hours")*52/12,model=incomeModel(),income=model.netMonthly,surplus=income-burn,cash=savings-setup,noWork=burn?cash/burn:99,deficit=Math.max(0,burn-income),workRunway=deficit?cash/deficit:99,months=Math.max(1,val("months")||12),firstPayWeeks=val("firstPayWeeks")||4,goal=val("savingsGoal"),bufferPct=val("bufferPct")||10;
const minimum=setup+burn*2,comfortable=setup+burn*3+burn*bufferPct/100,strong=setup+burn*6+burn*bufferPct/100;let score=Math.round(Math.max(0,Math.min(100,50+(cash>0?Math.min(30,cash/(burn||1)*5):-30)+(surplus>=0?20:Math.max(-20,surplus/(burn||1)*20)))));let st="Strong",cl="good";if(cash<=0||noWork<2){st="High risk";cl="bad"}else if(noWork<4||surplus<0){st="Tight";cl="warn"}
$("savingsCad").textContent=cadMoney(savings);$("resultCity").textContent=c.name;$("recommended").textContent=`${money(fromCad(minimum))}–${money(fromCad(comfortable))}`;$("recommendedCad").textContent=`CAD equivalent: ${cadMoney(minimum)}–${cadMoney(comfortable)}`;[["rSavings",savings],["rSetup",setup],["rCash",cash],["rRent",rent],["rOther",other],["rBurn",burn],["rIncome",income]].forEach(([id,v])=>{if($(id))$(id).textContent=money(fromCad(v))});$("rSurplus").textContent=signed(fromCad(surplus));$("rNoWork").textContent=cash<=0?"No buffer":`${Math.round(Math.max(0,noWork))} months`;$("rWithWork").textContent=deficit===0?"Self-sustaining":`${Math.round(Math.max(0,workRunway))} months`;$("cadSummary").textContent=`${cadMoney(minimum)}–${cadMoney(comfortable)} recommended starting cash`;$("score").textContent=score;$("scoreBar").style.width=score+"%";$("status").textContent=st;$("status").className=`status ${cl}`;
const callout=cash<=0?`Your savings do not cover the estimated arrival and setup costs.`:surplus>=0?`You're projected to cover your monthly costs once work starts.`:`Your estimated monthly deficit is ${money(Math.abs(fromCad(surplus)))}. Finding work quickly or reducing costs will improve your runway.`;$("callout").textContent=callout;
if($("takeHomePreview"))$("takeHomePreview").textContent=income?money(fromCad(income))+" / month":"—";if($("rGross"))$("rGross").textContent=money(fromCad(model.grossMonthly));if($("rTax"))$("rTax").textContent=money(fromCad(model.taxMonthly));if($("rPayroll"))$("rPayroll").textContent=money(fromCad(model.payrollMonthly));if($("rNet"))$("rNet").textContent=money(fromCad(model.netMonthly));if($("rRecommendedMin"))$("rRecommendedMin").textContent=money(fromCad(minimum));if($("rRecommendedComfort"))$("rRecommendedComfort").textContent=money(fromCad(comfortable));if($("rRecommendedStrong"))$("rRecommendedStrong").textContent=money(fromCad(strong));if($("realityCallout"))$("realityCallout").textContent=score>=80?`You're in a strong position based on these assumptions.`:score>=60?`Your plan looks workable, but keep an eye on your job-search runway.`:`Your buffer is tight. Consider saving more before you leave.`;
if($("scenario4")){const end2=projectedCash(cash,burn,income,6,2),end4=projectedCash(cash,burn,income,6,4),end10=projectedCash(cash,burn,income,6,10),end6=projectedCash(cash,burn,income,6,firstPayWeeks),end12=projectedCash(cash,burn,income,12,firstPayWeeks);$("scenario2").textContent=money(fromCad(end2));$("scenario4").textContent=money(fromCad(end4));$("scenario10").textContent=money(fromCad(end10));$("sixMonthSavings").textContent=money(fromCad(end6));$("twelveMonthSavings").textContent=money(fromCad(end12));$("savingsRate").textContent=income>0?Math.round((income-burn)/income*100)+"%":"—";const goalMonthly=goal>0?Math.max(0,(goal-end6)/Math.max(1,months-6)):0;$("goalMonthly").textContent=money(fromCad(goalMonthly));const breakeven=income>burn&&cash<setup+goal?(setup+goal-cash)/(income-burn):0;$("breakEven").textContent=breakeven>0?`${Math.ceil(breakeven)} months`:(cash>=setup+goal?"Already ahead":"Not reached");updateCashChart(cash,burn,income,Math.min(12,months))}}
function showCalculator(){$("origin")?.classList.add("hidden");$("calculator")?.classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});}
function switchDisplayCurrency(next){if(next===displayCurrency)return;const cadValues={};currencyInputs.forEach(id=>{if($(id))cadValues[id]=cadInput(id)});displayCurrency=next;currencyInputs.forEach(id=>{if($(id)&&cadValues[id]!=null)$(id).value=displayCurrency==="cad"?Math.round(cadValues[id]):roundInput(fromCad(cadValues[id]))});document.querySelectorAll(".currency-symbol").forEach(el=>el.textContent=displayCurrency==="cad"?"C$":currency().symbol);updateInputRanges();accommodationOptions();recalc()}
function renumberSteps(){const steps=[...document.querySelectorAll(".form-panel > .step")];let n=2;steps.forEach(step=>{if(step.classList.contains("extended-only")&&document.body.classList.contains("mode-quick"))return;const badge=step.querySelector(".step-head > span");if(badge)badge.textContent=String(n).padStart(2,"0");n++})}
function setMode(mode){document.body.classList.toggle("mode-quick",mode==="quick");document.body.classList.toggle("mode-full",mode==="full");document.querySelectorAll("#modeSwitch button").forEach(x=>x.classList.toggle("active",x.dataset.mode===mode));renumberSteps();recalc()}
function bindEvents(){const origin=$("originCountry");if(!origin)return;origin.addEventListener("change",e=>{if(e.target.value){homeCurrency=e.target.value;homeCountry=e.target.options[e.target.selectedIndex].dataset.country||currency().country;updateOriginPreview()}});$("startBudget")?.addEventListener("click",()=>{setCurrency(homeCurrency,{preserveCad:false});showCalculator();recalc()});$("changeCountry")?.addEventListener("click",()=>{$("calculator").classList.add("hidden");$("origin").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})});document.querySelectorAll(".city-card").forEach(b=>b.addEventListener("click",()=>{selectedCity=b.dataset.city;document.querySelectorAll(".city-card").forEach(x=>x.classList.toggle("selected",x.dataset.city===selectedCity));setCityDefaults()}));document.querySelectorAll(".lifestyle").forEach(b=>b.addEventListener("click",()=>{selectedLife=b.dataset.life;applyLifestyle()}));document.querySelectorAll("input,select").forEach(e=>e.addEventListener("input",()=>{if(e.id!=="originCountry")recalc()}));$("working")?.addEventListener("change",()=>{$("workFields")?.classList.toggle("disabled",!$("working").checked);recalc()});$("jobType")?.addEventListener("change",()=>{const j=APP_CONFIG.jobTypes[$("jobType").value];if(j){$("wage").value=displayCurrency==="cad"?Math.round(j.wage):roundInput(fromCad(j.wage));$("hours").value=j.hours;syncRanges();recalc()}});$("quickLifestyle")?.addEventListener("change",recalc);$("quickWork")?.addEventListener("change",recalc);$("printBtn")?.addEventListener("click",()=>window.print());rangePairs.forEach(x=>pair(x[0],x[1]));document.querySelectorAll("#modeSwitch button").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));$("homeCurrencyBtn")?.addEventListener("click",()=>switchDisplayCurrency("home"));$("cadCurrencyBtn")?.addEventListener("click",()=>switchDisplayCurrency("cad"));["bufferPct","savingsGoal","jobType","firstPayWeeks"].forEach(id=>$(id)?.addEventListener("input",recalc));currencyInputs.forEach(id=>$(id)?.addEventListener("input",()=>{const el=$(id);if(el){el.value=String(Math.round(Number(el.value)||0));recalc()}}))}
populateCountries();bindEvents();const saved=localStorage.getItem("whhqHomeCurrency");if(saved&&APP_CONFIG.currencies[saved]&&$("originCountry")){$("originCountry").value=saved;homeCurrency=saved;homeCountry=$("originCountry").options[$("originCountry").selectedIndex]?.dataset.country||currency().country;updateOriginPreview()}else updateOriginPreview();setMode("quick");
